### ISSUE TITLE
Growing a zink bush will crash you

### ISSUE THREAD

**Issue by IchigoGames** [Timebreaker900/MetalBushesMod#10]
Minecraft 1.16.5
Forge 36.1.32
Metal Bushes-v1.16.5-2.7
create-mc1.16.5_v0.3.2a

Crash report https://pastebin.com/GY5pmSem

all i did was load up a world place a zinc bush down and bone meal it and as soon as it was fully grown i crashed 
i was testing due to reports from players of my modpack of this happening on servers as well. 

edit it seems growing them is not what makes you crash it clicking on one once its fully grow that makes you crash.

**Comment by Timebreaker900** [comment]
Ok wait give me a second I look into it

**Comment by Timebreaker900** [comment]
Hey, sorry for the crash! The new version should be up on curseforge any minute!
