### ISSUE TITLE
Tag minecraft:diamond does not exist.

### ISSUE THREAD

**Issue by Darkhax** [Timebreaker900/MetalBushesMod#4]
When I run this mod there is an error when reading the [diamond_bush.json](https://github.com/Timebreaker900/MetalBushesMod/blob/1.15.2/src/main/resources/data/metalbushesmod/recipes/diamond_bush.json) file. The error is that the `minecraft:diamond` tag does not exist. On forge this tag should be `forge:gems/diamond`.

**Comment by Timebreaker900** [comment]
Thx I fixed it. I have another question inside my BushWolrdGen.java I let the bushes generate but how do I make them more rare?
