### ISSUE TITLE
Error when creating a world in modpack

### ISSUE THREAD

**Issue by Hydreigon057** [Timebreaker900/MetalBushesMod#5]
Hello, I made a modpack with a lot of mods and kept getting an error when trying to make or load a save.  I removed the metal bushes mod and it loads fine then.  It works fine on it's own, though.  [Here is a link](https://www.reddit.com/r/MinecraftForge/comments/j6aw4o/problems_creating_a_world_in_a_modpack_in_1161/) to my question over on r/minecraftforge where I was helped.  I go into more detail there.
I was told the datapack for this mod was broken and to make a report here.
The file I used was metalbushesmod-1.16.1-1.6.0.jar

**Comment by Timebreaker900** [comment]
Hey, hmm.. It's funny.. I had the same error with quark somedays on 1.16.1..  I'm not that experienced in modding so it's hard for me to tell what's wrong. I know that the requierd tag thingy: "java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Missing required tags: items:forge:nuggets/copper". should also work fine. 

If you add mekanism back to your pack does it break, cause I added a mekanism support to the mod.. maybe I implemented it wrong.

**Comment by Hydreigon057** [comment]
> Hey, hmm.. It's funny.. I had the same error with quark somedays on 1.16.1.. I'm not that experienced in modding so it's hard for me to tell what's wrong. I know that the requierd tag thingy: "java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Missing required tags: items:forge:nuggets/copper". should also work fine.
> 
> If you add mekanism back to your pack does it break, cause I added a mekanism support to the mod.. maybe I implemented it wrong.

Yeah, actually.  I wanted to remove mekanism because I wanted to use immersive engineering instead, and that is when I got the errors.  Adding mekanism and it's addon mods back in fixed the problem.

**Comment by Timebreaker900** [comment]
Ok I have the error myself now. It looks like that it has a problem if another mod generates copper..

**Comment by Timebreaker900** [comment]
Ok I fixed it in Version 1.6.1. Have fun!

What other supports should I add? Do you want to have an IE support?

**Comment by Hydreigon057** [comment]
> Ok I fixed it in Version 1.6.1. Have fun!
> 
> What other supports should I add? Do you want to have an IE support?

That would be super cool.  I personally am trying to make a skyblock quest modpack of my own because other packs seem lackluster to me
