### ISSUE TITLE
Not playing well with others

### ISSUE THREAD

**Issue by Chunkimunki** [Timebreaker900/MetalBushesMod#6]
Got this crash with the addition of Mekanism.
Is there anything that can be done to help them work together?
[Pastbin](https://pastebin.com/LHSz6njr)

Minecraft Version: 1.16.3
forge:34.1.35 
Metal Bushes Mod-v1.16.3-1.7.0.
Mekanism-1.16.3-10.0.15.441.

**Comment by Timebreaker900** [comment]
Thanks, Fixed in the new update
