### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by IchigoGames** [Timebreaker900/MetalBushesMod#7]
Minecraft 1.16.4
iv been using your mod in my pack and i also have BotanyPots some one using your mod on my server noticed that most of the bushes work in BotanyPots but not the modded bushhes aka copper tin osminum and also blaze

**Comment by IchigoGames** [comment]
any plan on making it work or does this need to be moved to botanypots ?

**Comment by Timebreaker900** [comment]
No clue, but I'm back at play Minecraft again and I will play with both mods.. and I will look at it :)

**Comment by Dr69onS6mur6i** [comment]
Not sure if its part of the same issue or not but the Blaze Bush isn't working in the BotanyPots either. It doesn't even show it being compatible with them in JEI. All of the other bushes, except the XP one, show a 'recipe' in JEI for the botany pots.

EDIT: Sorry for not mentioning it before but I'm playing Ichigo's modpack as well.

**Comment by Dr69onS6mur6i** [comment]
Since this thread is titled "Suggestions" I figured I'd put this here too.

Can you add compatibility with compacting drawers? For example, your Diamond Bush generates diamond nuggets but Compacting Drawers doesn't know what to do with them. If the bush generated Diamond Shards instead of nuggets then Compacting Drawers would work better.

**Comment by Timebreaker900** [comment]
Hey I think the dev from BotanyPots needs to add a compatibilty for the Blaze Bush to make it work. It should be placed on sand.

How do you know that diamond shards can be handled by Compacting Drawers?

**Comment by IchigoGames** [comment]
ok ill post it there then

**Comment by Dr69onS6mur6i** [comment]
I know that diamond shards work because when you put a diamond in the compacting drawer it gives you diamonds, diamond blocks, and diamond shards.
