### ISSUE TITLE
Issue with KUBEJS and IE Cloche Recipe

### ISSUE THREAD

**Issue by lays24mc** [Timebreaker900/MetalBushesMod#9]
Hi,

first thanks for this great mod :). Since there is currently no IE support I create the recipes with KUBEJS. But now there seems to be a problem with the Redstone Bush:

`Error creating recipe immersiveengineering:kjs_cba5hi9ln5c4ojb13df889pyl[immersiveengineering:cloche]: {"time":600,"type":"immersiveengineering:cloche","results":[{"item":"minecraft:redstone","count":2}],"input":{"item":"metalbushesmod:redstone_bush"},"soil":{"item":"minecraft:dirt"},"render":{"type":"crop","block":"minecraft:redstone_wire"}}: java.lang.IllegalArgumentException: Block block.minecraft.redstone_wire is not a valid crop block`

Der Code sieht wie folgt aus:

```
onEvent('recipes', ev => {
	
	function berrybushes(results, seed, crop) {
        ev.recipes.immersiveengineering.cloche(results, Item.of(seed), `minecraft:dirt`, crop).time(600)
    }
	
	//-- Berrybushes
	berrybushes([Item.of(`minecraft:redstone`, 2)], `metalbushesmod:redstone_bush`, `metalbushesmod:redstone_bush`)
	
})
```
The other bushes work fine :)

**Comment by Timebreaker900** [comment]
Hey, thanks for issue. I have actually no clue how kubejs work. Is this the only way I can add cloche recipes?

**Comment by lays24mc** [comment]
Hi,

maybe Crafttweaker. Only I do not use that, and therefore I had not tested :).

The interesting thing is, he only does not like the output (results). Affected are also only Redstone Dust and Block of Redstone ^^. If I take gold for example, it works :D

**Comment by Timebreaker900** [comment]
Hey I got it to work.. its actually pretty simple. I need to do a own cloche recipe. Next update I will fix it :D

**Comment by lays24mc** [comment]
Oh nice. Then I will be patient until then :)

And thank you

**Comment by Timebreaker900** [comment]
I think an hour or so :)

**Comment by Timebreaker900** [comment]
Version 2.7 is live. Hope everything works :D If not you know what to do ^^
